GKI: aoc/alsa: make args of_xlate_dai_name parameter constant
Upstream commit 933f98be60a7b ("ASoC: constify of_phandle_args in
snd_soc_get_dai_name()") requires args to be a constant parameter.

This fixes:
aoc/alsa/aoc_alsa_path.c:2009:23: error: incompatible function pointer types initializing
    'int (*)(struct snd_soc_component *, const struct of_phandle_args *, const char **)' with an expression of type
    'int (struct snd_soc_component *, struct of_phandle_args *, const char **)'
    [-Werror,-Wincompatible-function-pointer-types]
        .of_xlate_dai_name = aoc_of_xlate_dai_name,
                             ^~~~~~~~~~~~~~~~~~~~~
1 error generated.

Signed-off-by: Carlos Llamas <cmllamas@google.com>
Change-Id: I1d10148bbab4a7e54f6b85d62cec7ecf002bbaf4